[config]
skip_core_tasks = true

[tasks.pre-build]
description = "buildディレクトリを作成し直す"
script = [
'''
rm -rf build
mkdir build
'''
]

[tasks.build]
description = "cmake with emscripten, そしてビルドも行う."
script = [
'''
emcmake cmake -B build -S .
cmake --build build --parallel
'''
]

[tasks.run-test]
description = "nodejsでテストを実行する."
script = [
'''
cmake --build build --parallel
node ./build/tests.js
'''
]

[tasks.default]
description = "display help message"
script = [
'''
makers --list-all-steps
'''
]
